### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by Phase-Issue** [AmosKorir/AvatarImageGenerator#14]
Hey, nice libary.
How to use it to get the image in notifications?

i use it like this way but its crashing 

On all Activities this is working exept in notifications

return try {
        // Here, use glide or do your things on UiThread
        val profileImg = GlideApp.with(this)
                .asBitmap()
                .load(strURL)
                .placeholder(AvatarGenerator.avatarImage(this, 200, AvatarConstants.CIRCLE, Prefs.getUserName))
                .transform(DkcGlide.circleCrop)
                .submit(_40_DP, _40_DP)
                .get()
        profileImg
    } catch (e: IOException) {
        e.printStackTrace()
        null
    }

**Comment by AmosKorir** [comment]
Can you share the error Logs?

**Comment by Phase-Issue** [comment]
I have fixed it by using it like this way.

Glide.with(this)
                            .asBitmap()
                            .load(retrieveUserImage())
                            .placeholder(AvatarGenerator.avatarImage(this, 200, AvatarConstants.CIRCLE, Prefs.getUserName))
                            .transform(DkcGlide.circleCrop)
                            //.submit(_40_DP, _40_DP)
                            .into(object: CustomTarget<Bitmap>() {

                                override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
                                    Log.e("onResourceReady -->", resource.toString())
                                    completeImage = resource
                                    sendFCMNotification(createID(), title, message, "", completeImage)
                                }

                                override fun onLoadFailed(errorDrawable: Drawable?) {
                                    super.onLoadFailed(errorDrawable)
                                    completeImage = AvatarGenerator.avatarImage(this@DkcFirebaseIdService, 200, AvatarConstants.CIRCLE, Prefs.getUserName).bitmap
                                    sendFCMNotification(createID(), title, message, "", completeImage)
                                }

                                override fun onLoadCleared(placeholder: Drawable?) {
                                    TODO("Not yet implemented")
                                }
                            })

Thank you for the nice library

**Comment by AmosKorir** [comment]
Welcome @Phase-Issue .  I will then close the issue.
 Thanks.
