### ISSUE TITLE
Gradle doesn't recognize v1.5.0 when I upgrade from v1.4

### ISSUE THREAD

**Issue by Breens-Mbaka** [AmosKorir/AvatarImageGenerator#21]
When I upgrade to 1.5.0 my Gradle doesn't recognize the latest 1.5.0 version. I'm using Android Studio BumbleBee this is the only library that seems I can't be able to update to the latest version. 
![avatar](https://user-images.githubusercontent.com/72180010/152095434-fece4c48-016b-4a2b-988e-8d6f866210f4.png)

**Comment by AmosKorir** [comment]
Hi Breen ,
Bintray was deprecated.

This the new jitpack dependency.
`'implementation 'com.github.amoskorir:avatarimagegenerator:1.5.0'`
