### ISSUE TITLE
Unable to resolve error ??

### ISSUE THREAD

**Issue by drmkraja** [AmosKorir/AvatarImageGenerator#9]
It shows unable to resolve error in my java project ?

![ava](https://user-images.githubusercontent.com/25397733/87567692-3908ad80-c6e2-11ea-93f1-216258c4d966.png)

**Comment by AmosKorir** [comment]
Hello have you been able to fix it ?

**Comment by AmosKorir** [comment]
Use companion for java. 
` Glide.with(imageView)
                .asBitmap()
                .load("https://github.com/AmosKorir/AvatarImageGenerator/blob/master/art/Screen2.png")
                .placeholder(AvatarGenerator.Companion.avatarImage(this,200,AvatarConstants.Companion.getCIRCLE(),"kotjav"))
                .into(imageView);`
